### ISSUE TITLE
error(-212) lib/d_ldb/Calibration.txt(8): Invalid or unsupported syntax in function icvYMLParse

### ISSUE THREAD

**Issue by ghost** [roberto-arroyo/OpenABLE#3]
Hola Roberto, estaba probando los distintos descriptores que ofrece OpenAble. Al probar el D-LDB con el  Test_OpenABLE tengo el siguiente error (todos los demas funcionan correctamente):

Reading image: ../../datasets/KITTI/00/image_0/000000.png
Reading image: ../../datasets/KITTI/00/image_1/000000.png
OpenCV Error: Parsing error (lib/d_ldb/Calibration.txt(8): Invalid or unsupported syntax) in icvYMLParse, file /home/emiliano/opencv/opencv-3.0.0/modules/core/src/persistence.cpp, line 1382
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/emiliano/opencv/opencv-3.0.0/modules/core/src/persistence.cpp:1382: error: (-212) lib/d_ldb/Calibration.txt(8): Invalid or unsupported syntax in function icvYMLParse

Abortado (`core' generado)

Estoy probando con los Datasets Stereo en escala de grises  de KITTI. Deberia cambiar el Calibration.txt? . Los que vienen con este Dataset se ven bastante distintos al que figura en el ejemplo de testeo.

Muchas Gracias

**Comment by roberto-arroyo** [comment]
¡Hola!

Por el error que me comentas, es algún problema a la hora de cargar el fichero yml y pasar los parámetros. Revisa que todo el fichero de configuración esté correcto.

Por otro lado, las secuencias de KITTI usan distintos parámetros de calibración. Los que están por defecto son para KITTI Odometry, si quieres usar KITTI Stereo, probablemente tengas que cambiar los valores de las matrices de la calibración, distorsión y las distintas configuraciones que hay y adaptarlas al caso concreto.

Gracias a ti.

Saludos

**Comment by roberto-arroyo** [comment]
Por otro lado, acabo de ver que el fichero de calibración de ejemplo tiene un punto suelto en la línea 8 que igual te está afectando, bórralo para que te funcione correctamente ya que por la línea que te marca igual es eso. Lo corregiré en futuras updates del código.

Gracias de nuevo,

¡Saludos!

**Comment by ghost** [comment]
Funciono correctamente al sacar el punto. Gracias

Saludos!
